### ISSUE TITLE
Issue when using MultipartiteRank

### ISSUE THREAD

**Issue by MGoulley** [boudinfl/pke#24]
Hello @boudinfl ,
I have an issue when i use MultipartiteRank, i get 

> File "xml_to_kw.py", line 11, in <module>
    extractor.candidate_weighting()
  File "/home/matthias/.local/lib/python2.7/site-packages/pke/unsupervised/graph_based.py", line 481, in candidate_weighting
    self.weight_adjustment(alpha)
  File "/home/matthias/.local/lib/python2.7/site-packages/pke/unsupervised/graph_based.py", line 442, in weight_adjustment
    for start, end in self.graph.edges_iter(first):
AttributeError: 'DiGraph' object has no attribute 'edges_iter'

Here is my code : 

```
import pke
import sys
import os

extractor = pke.unsupervised.MultipartiteRank(input_file= sys.argv[1], language='french')
extractor.build_topic_graph()
extractor.read_document(format='corenlp', use_lemmas=False, stemmer='french')
extractor.candidate_selection()
extractor.candidate_weighting()
extractor.topic_clustering()
extractor.weight_adjustment()
tuples = extractor.get_n_best(n=60)
print(tuples)
```

I think it's a problem about the order in which i use functions, but i don't find example about that... :(

Thanks

**Comment by boudinfl** [comment]
Here is a corrected snippet of code for using MultipartiteRank. The API is the same as for the other models.

```
import os, sys
import pke

# create a MultipartiteRank extractor and set the input language to french (used for
# the stoplist in the candidate selection method)
extractor = pke.unsupervised.MultipartiteRank(input_file= sys.argv[1], language='french')

# load the content of the document, here in CoreNLP XML format
# the stemmer parameter allows to use stems computed using nltk
extractor.read_document(format='corenlp', use_lemmas=False, stemmer='french')

# select the keyphrase candidates, for TopicRank the longest sequences of 
# nouns and adjectives (UD French tagset)
extractor.candidate_selection(pos=['ADJ', 'NOUN', 'PROPN'])

# weight the candidates using a random walk with default parameters.
extractor.candidate_weighting()

# get the n-highest (60) scored candidates
tuples = extractor.get_n_best(n=60)
print(tuples)
```
Best,

Florian

**Comment by MGoulley** [comment]
I get the same issue when i use your snippet : 

> Traceback (most recent call last):
  File "xml_to_kw.py", line 10, in <module>
    extractor.candidate_weighting()
  File "/home/matthias/.local/lib/python2.7/site-packages/pke/unsupervised/graph_based.py", line 481, in candidate_weighting
    self.weight_adjustment(alpha)
  File "/home/matthias/.local/lib/python2.7/site-packages/pke/unsupervised/graph_based.py", line 442, in weight_adjustment
    for start, end in self.graph.edges_iter(first):
AttributeError: 'DiGraph' object has no attribute 'edges_iter'

(I use networkx-2.1 in Python2.7 )


Thanks for your response @boudinfl ;)
Matt

**Comment by boudinfl** [comment]
networkx 2.0 removed edges_iter(), I fix this issue in the 1.7 release.
