### ISSUE TITLE
Error with TextRank

### ISSUE THREAD

**Issue by boudinfl** [boudinfl/pke#55]
I get the following error when extracting keyphrases from file 2000_10_09-13_00_00-JornaldaTarde-8-topic-seg.txt-Nr1 that appears in the 110-PT-BN-KP dataset.

```
INFO:root:running [output/110-PT-BN-KP//110-PT-BN-KP.TextRank.json]
INFO:root:extracting keyphrases from [2000_10_09-13_00_00-JornaldaTarde-8-topic-seg.txt-Nr1]
Traceback (most recent call last):
  File "run.py", line 272, in <module>
    extractor.candidate_weighting()
  File "/usr/local/lib/python3.6/site-packages/pke/unsupervised/graph_based/textrank.py", line 239, in candidate_weighting
    self.weights[k] = sum([w[t] for t in tokens])
  File "/usr/local/lib/python3.6/site-packages/pke/unsupervised/graph_based/textrank.py", line 239, in <listcomp>
    self.weights[k] = sum([w[t] for t in tokens])
KeyError: 'encontr'
```

**Comment by ra1nbowpill** [comment]
See [this commit](https://github.com/boudinfl/ake-benchmarking/commit/74d7582d1e5f68897461fafd546be0b0a104d261)
There was a difference between the POS when extracting candidates and the POS used to create the graph
