### ISSUE TITLE
error: sre_constants.error: look-behind requires fixed-width pattern

### ISSUE THREAD

**Issue by sylwiaoz** [boudinfl/pke#98]
Hello,

When I try to run pke, I get the follwing trace with an error message at the end:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sylwia/.local/lib/python2.7/site-packages/pke/base.py", line 112, in load_document
    doc = parser.read(text=input, **kwargs)
  File "/home/sylwia/.local/lib/python2.7/site-packages/pke/readers.py", line 74, in read
    max_length=max_length)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/util.py", line 196, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "/home/sylwia/.local/lib/python2.7/site-packages/spacy/language.py", line 823, in <lambda>
    p, exclude=["vocab"]
  File "tokenizer.pyx", line 391, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 439, in spacy.tokenizer.Tokenizer.from_bytes
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: look-behind requires fixed-width pattern

I would appreciate your help with that.

Cheers
Sylwia

**Comment by boudinfl** [comment]
Hum, It looks like you are using Python 2.7 and `pke` is only compatible with Python 3.7+. Can you try using python 3.

**Comment by sylwiaoz** [comment]
Hi @boudinfl,

Thank you for your message. I have python 3 installed (along with python 2.7). What do I need to do to run pke with python 3?

Cheers
Sylwia

**Comment by sylwiaoz** [comment]
Thank you for your message @boudinfl.

I wasn't sure how to go about it using python 3 (I have both 2 and 3 installed) but it seems all good now.
